/*
 * generated by Xtext 2.25.0
 */
package msdexam.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import msdexam.MsdExamRuntimeModule;
import msdexam.MsdExamStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MsdExamIdeSetup extends MsdExamStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MsdExamRuntimeModule(), new MsdExamIdeModule()));
	}
	
}
