/*
 * generated by Xtext 2.25.0
 */
package msdexam.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MsdExamUiModule extends AbstractMsdExamUiModule {

	public MsdExamUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
